# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  port: <%= ENV.fetch('DB_PORT', '5432') %>
  pool: <%= ENV.fetch('DB_MAX_THREADS', 5) %>
  host: <%= ENV.fetch('DB_HOST', 'db') %>
  database: <%= ENV.fetch('DB_DATABASE', 'warehousr-management') %>
  username: <%= ENV.fetch('DB_USER', 'postgres') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'postgres') %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV.fetch('DB_DATABASE', 'warehousr-management') %>_development

test:
  <<: *default
  database: <%= ENV.fetch('DB_DATABASE', 'warehousr-management') %>_test

staging:
  <<: *default

production:
  <<: *default
